import json
from typing import List


class RequirementExtractor:
    """Extracts atomic requirement statements from stakeholder text via JSON-mode Gemini call."""

    def __init__(self, *, llm):
        self.llm = llm

    async def extract(self, stakeholder_text: str) -> List[dict]:
        prompt = (
            "Extract distinct, testable requirements from the stakeholder text below.\n\n"
            "STYLE — write each statement as a complete, grammatical sentence:\n"
            "- A full sentence with a clear subject and verb, ending with a period.\n"
            "  Never emit a bare noun phrase or fragment.\n"
            "- Functional requirements name WHO does what. Start with the actor:\n"
            "  'Users can ...', 'The system ...', 'An administrator can ...'.\n"
            "- Non-functional requirements describe a system quality with its threshold,\n"
            "  and read naturally as 'The system should ...' or 'The system must ...'.\n"
            "- Keep each to ONE sentence, roughly 6 to 20 words. Clear and direct;\n"
            "  avoid deeply nested clauses and vague filler.\n"
            "- Examples of GOOD phrasing:\n"
            "    'Users can browse the menu and place an order.'\n"
            "    'The system sends an order confirmation email after checkout.'\n"
            "    'An administrator can update menu items and prices.'\n"
            "    'The system should support up to 50,000 concurrent orders during peak hours.'\n"
            "    'The system must respond to search queries within 2 seconds.'\n"
            "- Examples of BAD phrasing (fragments or vague — do NOT emit these):\n"
            "    'Menu browsing.'                 (fragment — no subject or verb)\n"
            "    'Order placement and payment.'   (fragment)\n"
            "    'Fast and reliable.'             (vague, not measurable)\n\n"
            "QUANTITY RULE:\n"
            "- Extract at most 5 requirements per stakeholder reply. Pick only the most\n"
            "  concrete, testable, and distinct capabilities. If the reply mentions 7 things\n"
            "  but 2 are vague, emit only the strong ones.\n"
            "- Prefer FEWER high-quality requirements over MANY low-quality ones.\n\n"
            "CONTENT RULES:\n"
            "- One requirement = one user-visible capability or constraint. Combine multi-step "
            "interactions (drag-and-drop, search-and-filter, login-with-OTP) into a single line.\n"
            "- Deduplicate: if two phrasings describe the same capability, keep only one.\n"
            "- BUT a measurable threshold is its OWN requirement: when a reply gives an explicit\n"
            "  metric (a time/latency limit, percentage, count, rate, or named standard), ALWAYS\n"
            "  emit a non_functional requirement for it — even if a functional requirement already\n"
            "  covers the same feature. E.g. 'register a QR check-in within 5 seconds' yields BOTH\n"
            "  a functional check-in requirement AND a separate non_functional 5-second one.\n"
            "- Skip vague filler that isn't actionable ('be user-friendly' on its own).\n"
            "- Skip anything the stakeholder only IMPLIED but didn't explicitly state.\n\n"
            "CLASSIFY BY INTENT, NOT BY KEYWORDS:\n"
            "- functional: a behavior, capability, or feature the user can observe or trigger.\n"
            "    Examples: 'Users can sync task-complete state to Google Calendar.',\n"
            "              'Users can drag and drop tasks onto calendar slots.',\n"
            "              'The system updates a task's visual state when it is completed.',\n"
            "              'The system retries failed syncs in the background.'\n"
            "- non_functional: a MEASURABLE quality with a threshold or metric (time,\n"
            "    percentage, count, standard). NOT just adjectives like 'fast' or 'reliable'.\n"
            "    Examples: 'The system should keep P95 latency under 3 seconds.',\n"
            "              'The system should maintain 99.9% monthly uptime.',\n"
            "              'The system should support up to 1,000 concurrent users.',\n"
            "              'The system must comply with WCAG 2.1 AA accessibility standards.'\n"
            "- constraint: an external limitation that restricts HOW the project is built,\n"
            "    separate from WHAT it does. Emit ONLY when the stakeholder explicitly\n"
            "    stated a limitation that is NOT already implicit in a functional\n"
            "    requirement. The core platform the app is built on (e.g. 'on Google\n"
            "    Calendar', 'as a mobile app') is NOT a constraint — it is captured by\n"
            "    the functional requirements that mention it. Don't restate it.\n"
            "    Good examples: 'The system must ship before 2026-08-01.' (deadline),\n"
            "                   'The system must comply with GDPR Article 17.' (regulatory),\n"
            "                   'Operational cost must stay under $500 per month.' (budget),\n"
            "                   'The system cannot use third-party AI services.' (exclusion),\n"
            "                   'The frontend must be built with React 18 or newer.' (tech mandate).\n"
            "    BAD example (do NOT emit as a constraint): 'Users can integrate with\n"
            "    Google Calendar.' — that's the app's platform, already in the FRs.\n"
            "    If you have nothing that meets this bar, return zero constraints.\n\n"
            "WORDS THAT TRICK YOU — these are qualifiers on a functional behavior, NOT NFRs:\n"
            "  'instantly', 'in background', 'silently', 'fast', 'responsive', 'user-friendly',\n"
            "  'seamless', 'smooth', 'automatic'.\n"
            "A statement is non_functional ONLY if it carries a verifiable threshold. So:\n"
            "  'The system updates the UI instantly when a task is checked.' -> functional (behavior).\n"
            "  'The system updates the UI within 100ms of a task check.'     -> non_functional (metric).\n"
            "  'The system syncs to Google Calendar in the background.'      -> functional (capability).\n"
            "  'The system completes 99.9% of syncs within 5 seconds.'       -> non_functional (metric).\n\n"
            "Return JSON: {\"requirements\": [{\"statement\": str, \"type\": str}]}\n\n"
            f"Text:\n\"\"\"{stakeholder_text}\"\"\""
        )
        raw = await self.llm.generate(prompt, temperature=0.2, response_mime_type="application/json")
        reqs = json.loads(raw).get("requirements", [])
        return reqs[:5]
