from typing import List

from .llm_service import first_json_object


class RequirementExtractor:
    """Extracts atomic requirement statements from stakeholder text via JSON-mode Gemini call."""

    def __init__(self, *, llm):
        self.llm = llm

    async def extract(self, stakeholder_text: str) -> List[dict]:
        prompt = (
            "Extract distinct, testable requirements from the stakeholder text below.\n\n"
            "STYLE — write each statement as a complete, grammatical sentence:\n"
            "- A full sentence with a clear subject and verb, ending with a period.\n"
            "  Never emit a bare noun phrase or fragment.\n"
            "- Functional requirements name WHO does what. Start with the actor:\n"
            "  'Users can ...', 'The system ...', 'An administrator can ...'.\n"
            "- Non-functional requirements pair a system quality with a measurable threshold\n"
            "  (a speed, reliability, or scale metric). The modal verb ('should'/'must') never\n"
            "  decides the type — a 'The system must ...' sentence is often functional.\n"
            "- Keep each to ONE sentence, roughly 6 to 20 words. Clear and direct;\n"
            "  avoid deeply nested clauses and vague filler.\n"
            "- Examples of GOOD phrasing:\n"
            "    'Users can browse the menu and place an order.'\n"
            "    'The system sends an order confirmation email after checkout.'\n"
            "    'An administrator can update menu items and prices.'\n"
            "    'The system should support up to 50,000 concurrent orders during peak hours.'\n"
            "    'The system must respond to search queries within 2 seconds.'\n"
            "- Examples of BAD phrasing (fragments or vague — do NOT emit these):\n"
            "    'Menu browsing.'                 (fragment — no subject or verb)\n"
            "    'Order placement and payment.'   (fragment)\n"
            "    'Fast and reliable.'             (vague, not measurable)\n\n"
            "QUANTITY RULE:\n"
            "- Extract at most 5 requirements per stakeholder reply. Pick only the most\n"
            "  concrete, testable, and distinct capabilities. If the reply mentions 7 things\n"
            "  but 2 are vague, emit only the strong ones.\n"
            "- Prefer FEWER high-quality requirements over MANY low-quality ones.\n\n"
            "CONTENT RULES:\n"
            "- One requirement = one user-visible capability or constraint. Combine multi-step "
            "interactions (drag-and-drop, search-and-filter, login-with-OTP) into a single line.\n"
            "- Deduplicate: if two phrasings describe the same capability, keep only one.\n"
            "- A PERFORMANCE threshold is its OWN requirement: when a reply says HOW FAST,\n"
            "  how reliably, how securely, or AT WHAT SCALE a feature must run (a latency limit,\n"
            "  uptime %, throughput, concurrent-user count, or named quality standard), ALWAYS\n"
            "  emit a non_functional requirement for it — even if a functional requirement already\n"
            "  covers the same feature. E.g. 'register a QR check-in within 5 seconds' yields BOTH\n"
            "  a functional check-in requirement AND a separate non_functional 5-second latency one.\n"
            "- A TRIGGER threshold is NOT its own requirement and is NOT non_functional: when a\n"
            "  number sets the business CONDITION that makes a feature fire (after N minutes of\n"
            "  inactivity, after N failed attempts, once a total exceeds N), it lives INSIDE the\n"
            "  single functional requirement it triggers — do not spin off a separate row for it.\n"
            "  E.g. 'flag a mechanic as idle after 15 minutes of inactivity' is ONE functional\n"
            "  requirement; the 15 minutes is the trigger, not a performance metric.\n"
            "- Skip vague filler that isn't actionable ('be user-friendly' on its own).\n"
            "- Skip anything the stakeholder only IMPLIED but didn't explicitly state.\n\n"
            "CLASSIFY BY INTENT, NOT BY KEYWORDS:\n"
            "- functional: a behavior, capability, business rule, or feature the user can observe\n"
            "    or that the system executes. A functional requirement may still contain a number\n"
            "    when that number is the CONDITION or TRIGGER for the behaviour — a timeout, a\n"
            "    count, or a threshold that fires an action.\n"
            "    Examples: 'Users can sync task-complete state to Google Calendar.',\n"
            "              'Users can drag and drop tasks onto calendar slots.',\n"
            "              'The system updates a task's visual state when it is completed.',\n"
            "              'The system flags a mechanic as idle after 15 minutes of inactivity.',\n"
            "              'The system locks an account after 5 failed login attempts.'\n"
            "- non_functional: a measurable quality describing HOW WELL a feature runs — its\n"
            "    speed, reliability, security, or scale — NOT the condition that triggers it.\n"
            "    It needs a verifiable metric, not just adjectives like 'fast' or 'reliable'.\n"
            "    Examples: 'The system should keep P95 latency under 3 seconds.',\n"
            "              'The system should maintain 99.9% monthly uptime.',\n"
            "              'The system should support up to 1,000 concurrent users.',\n"
            "              'The system must comply with WCAG 2.1 AA accessibility standards.'\n"
            "- constraint: an external limitation that restricts HOW the project is built,\n"
            "    separate from WHAT it does. Emit ONLY when the stakeholder explicitly\n"
            "    stated a limitation that is NOT already implicit in a functional\n"
            "    requirement. The core platform the app is built on (e.g. 'on Google\n"
            "    Calendar', 'as a mobile app') is NOT a constraint — it is captured by\n"
            "    the functional requirements that mention it. Don't restate it.\n"
            "    Good examples: 'The system must ship before 2026-08-01.' (deadline),\n"
            "                   'The system must comply with GDPR Article 17.' (regulatory),\n"
            "                   'Operational cost must stay under $500 per month.' (budget),\n"
            "                   'The system cannot use third-party AI services.' (exclusion),\n"
            "                   'The frontend must be built with React 18 or newer.' (tech mandate).\n"
            "    BAD example (do NOT emit as a constraint): 'Users can integrate with\n"
            "    Google Calendar.' — that's the app's platform, already in the FRs.\n"
            "    If you have nothing that meets this bar, return zero constraints.\n\n"
            "WORDS THAT TRICK YOU — these are qualifiers on a functional behavior, NOT NFRs:\n"
            "  'instantly', 'in background', 'silently', 'fast', 'responsive', 'user-friendly',\n"
            "  'seamless', 'smooth', 'automatic'.\n"
            "NUMBERS THAT TRICK YOU — a threshold alone does NOT make a statement non_functional.\n"
            "The golden rule: if the number is a TRIGGER that makes a feature happen, it is\n"
            "functional; if it dictates HOW FAST, secure, reliable, or scalable that feature must\n"
            "be, it is non_functional. Removal test: drop the number — if WHAT the feature does or\n"
            "WHEN it fires becomes undefined, it was a trigger (functional); if the feature still\n"
            "does the same thing and only its speed/scale is lost, it was a metric (non_functional).\n"
            "  'The system updates the UI instantly when a task is checked.'       -> functional (behavior).\n"
            "  'The system updates the UI within 100ms of a task check.'           -> non_functional (speed).\n"
            "  'The system flags a session once it is active for over 45 minutes.' -> functional (trigger).\n"
            "  'The system detects a stuck mechanic after 15 diagnostic prompts.'  -> functional (trigger).\n"
            "  'The system completes 99.9% of syncs within 5 seconds.'             -> non_functional (metric).\n\n"
            "Return JSON: {\"requirements\": [{\"statement\": str, \"type\": str}]}\n\n"
            f"Text:\n\"\"\"{stakeholder_text}\"\"\""
        )
        raw = await self.llm.generate(prompt, temperature=0.2, response_mime_type="application/json")
        # A genuinely unparseable payload still raises: the dialogue router
        # degrades that to "no requirements this turn" rather than a 500.
        reqs = first_json_object(raw).get("requirements", [])
        return reqs[:5]
